[package]
name = "kmer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kmer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
hashbrown = "0.13.2"
rayon = "*"

